router:
  build: kbrouter
  environment:
  ports:
   - "5000:5000"
  volumes:
   - ./cluster.ini:/code/cluster.ini
   - /var/run/docker.sock:/var/run/docker.sock
www:
  build: proxy/
  links:
   - router
  ports:
   - "8080:80"
   - "8443:443"
  volumes:
   - ./ssl:/etc/nginx/ssl/
aweworkerdev:
  image: kbase/depl:latest
  restart: always
  links:
   - www:www
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /mnt/awe/dev/work:/mnt/awe/dev/work
  command: aweworker dev
narrative:
  image: kbase/depl:latest
  environment:
   - MYSERVICES:narrative
  links:
   - www:www
  ports:
   - "6080:80"
   - "6443:443"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  command: narrative
